### Send POST request with json body
POST http://localhost:8080/create-member
Content-Type: application/json

{
  "userId": "milk6647",
  "userPw": "99999999",
  "name": "DevCat2",
  "age": 30,
  "experienceYears": 5,
  "jobType": "Developer" ,
  "foodCountry": "Korea"
}