### Send POST request with json body
POST http://localhost:8080/create-user
Content-Type: application/json

{
  "userId": "msmdasfasdfms",
  "userPw": "smsmsmsm",
  "name": "DevCat",
  "age": 30,
  "jobType": "Developer" ,
  "foodCountry": "Korea"
}